#!/bin/sh

#
# jupyter tool
#
/usr/bin/invoke_app "$@" \
-C "start_jupyter -t -T @tool Silly_Test_Example.ipynb" \
                           -t netdebugger \
                           -u anaconda-7 \
                           -w headless \
                           -r none
